# Generated by Django 2.2.16 on 2022-12-06 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20221205_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст комментария', verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(blank=True, help_text='Автор комментария', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Комментарий')),
                ('post', models.ForeignKey(blank=True, help_text='Комментарий к посту', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.Post', verbose_name='Комментарий')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
